env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - warn
globals:
  angular: true
  litteraApp: true
  $: true
  noty: true
  moment: true
  Masonry: true

